spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001  # dept微服务占用8001端口，冒号后面必须有空格
 
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.yf.springcloud.entities
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml   

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info: # 完善info信息
  app.name: yf-microservicecloud
  company.name: www.yf.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001  # dept微服务占用8001端口，冒号后面必须有空格
 
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.yf.springcloud.entities
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml   

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info: # 完善info信息
  app.name: yf-microservicecloud
  company.name: www.yf.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$